---
title: "MoveDB: Toward a Scalable Biomechanics Database Platform for Reproducible Research"
author:
  name: "Hudson Burke"
  affiliation: "University of Virginia"
---

*Disclaimer: I submitted a similar abstract under the same name in the call for abstracts prior to being made aware of the pitch competition.*

## Unmet Need & Market Potential

Biomechanics research lacks a cohesive strategy to handle "Big Data". At the American Society for Biomechanics 2025 meeting, a majority voted that biomechanics was not capable of properly utilizing large-scale datasets. Progress is hindered by disparate, file-based workflows that  create inefficient and obtuse access strategies that are difficult to replicate even within one research group. MoveDB aims to be an open-source software platform addressing these challenges by providing scalable tools for data management, analysis, and sharing.

## Technology Novelty & Utility

While MATLAB has been the standard for biomechanics, its license, closed-source nature, and limited packages create barriers for reproducibility and collaboration. MoveDB has been developed using Python to leverage its strengths in data science, free and open source ecosystem, and portability. The platform supports efficient data ingestion, allowing users to upload C3D files, perform complex queries to filter datasets and utilize OpenSim's API to run analyses programmatically. MoveDB also enables flexible deployment options, from local installations for individual researchers to cloud-based solutions for larger collaborations. 

## Technical Feasibility

The platform utilizes a dual-layered data architecture: SQL for efficient metadata querying and HDF5 for time series data. Built with FastAPI and SQLModel, MoveDB provides high-performance data operations through a user-friendly interface. For common biomechanics workflows, we incorporate EZC3D for reading C3D files, and OpenSim's Python API for biomechanical modeling and simulation. The modular design of MoveDB allows for easy integration of additional data formats and analysis tools in the future, ensuring the platform's longevity in biomechanics research. The core ingestion and database mapping logic have been validated through pilot testing.

## Translational Pathway

MoveDB is committed to a permanent open-source model, and community involvement is essential for its success. The roadmap focuses on expanding API capabilities and developing a web-based user interface to increase accessibility for non-computational researchers. We anticipate an initial release within the next year, followed by iterative, community-driven improvements to meet the evolving needs of the global biomechanics field.
